### ISSUE TITLE
Add Filter to Multivalue Widget

### ISSUE THREAD

**Issue by williwacker** [jannekalliola/openhab-widgets#4]
I am using your Multivalue widget for e.g. displaying the LowBattery values (ON/OFF).  But it would be terrific having a filter function so only the ON values would be shown.  Do you think you could enhance your widget with this?
Thanks

**Comment by jannekalliola** [comment]
I'm not sure whether I understood your request correctly. Do you want to show the text in each row only when value is ON and no text at all when the value is OFF?

**Comment by williwacker** [comment]
Yes, you are correct. I would only like to see devices that have a problem. Instead of using a filter I could think of having two more options like showOnlyOnValues and showOnlyOffValues and skipping the devices with the opposite state.
Thanks

**Comment by jannekalliola** [comment]
I've now added a new option to show the switch items based on their values. The item still takes the same space, so that it is clickable, but it does not show the name.
